name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: zmk-org/zmk/.github/workflows/build.yml@v3.5.0
    with:
      build_matrix_file: build.yaml
      cmake_args: -DSHIELD_ROOT=/__w/asteroid-CustomKeyboard/asteroid-CustomKeyboard/boards/shields
