name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: zmk-org/zmk/.github/workflows/build.yml@main
    with:
      build_matrix_file: build.yaml
