name: Build ZMK firmware
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v3.5.0
    with:
      build_matrix_file: build.yaml
      cmake_args: -DSHIELD_ROOT="${{ github.workspace }}/boards/shields"
